media:
  - name: Products
    input: assets/images/products
    output: assets/images/products

  - name: Blogs
    input: assets/images/blogs
    output: assets/images/blogs

  - name: EmbroideryAssets
    input: assets/images/embroidery
    output: assets/images/embroidery
    
content:
  - name: posts
    label: Blog
    type: collection
    path: _posts
    extension: html
    format: yaml-frontmatter
    filename: "{year}-{month}-{day}-{slug}"
    fields:
      - name: layout
        label: Raspored
        type: string
        default: post
        hidden: true
      - name: title
        label: Naslov
        type: string
        required: true
      - name: date
        label: Datum
        type: date
        required: true
      - name: author
        label: Autor
        type: string
        default: Lazy Pleasure
      - name: description
        label: Opis
        type: text
        required: false
      - name: image
        label: Naslovna slika
        type: image
        options:
          media: Blogs
      - name: tags
        label: Tagovi
        type: string
        list: true
      - name: body
        label: Sadržaj
        type: rich-text

  - name: product-pages
    label: Proizvodi (Stranice)
    type: collection
    path: proizvod
    extension: md
    format: yaml-frontmatter
    fields:
      - name: layout
        label: Layout
        type: string
        default: product
        hidden: true
      - name: title
        label: Naziv proizvoda
        type: string
        required: true
      - name: product_id
        label: ID proizvoda
        type: string
        required: true
      - name: category
        label: Kategorija
        type: string
        required: true
      - name: base_price
        label: Osnovna cena (RSD)
        type: number
        required: true
      - name: price
        label: Cena (RSD)
        type: number
        required: true
      - name: old_price
        label: Stara cena (RSD)
        type: number
      - name: in_stock
        label: Na stanju
        type: boolean
        default: true
      - name: featured
        label: Istaknuto
        type: boolean
        default: false
      - name: supports_embroidery
        label: Podržava vez
        type: boolean
        default: false
      - name: supports_name_embroidery
        label: Podržava vez imena
        type: boolean
        default: false
      - name: description
        label: Opis
        type: rich-text
        required: true
      - name: images
        label: Slike
        type: image
        list: true
        options:
          media: assets/images/products
      - name: colors
        label: Boje
        type: object
        list: true
        fields:
          - name: name
            label: Naziv boje
            type: string
            required: true
          - name: hex
            label: Hex kod
            type: string
            required: true
          - name: price_modifier
            label: Modifikator cene
            type: number
            default: 0
          - name: image
            label: Slika boje (default)
            type: image
            options:
              media: Products
          - name: size_images
            label: Slike po veličinama
            type: object
            list: true
            fields:
              - name: size
                label: Veličina
                type: string
                required: true
              - name: image
                label: Slika
                type: image
                options:
                  media: Products
      - name: sizes
        label: Veličine
        type: object
        list: true
        fields:
          - name: name
            label: Naziv veličine
            type: string
            required: true
          - name: price_modifier
            label: Modifikator cene
            type: number
            default: 0
      - name: tags
        label: Tagovi
        type: string
        list: true

  - name: products
    label: Proizvodi
    type: file
    path: _data/products.json
    format: json
    fields:
      - name: root
        label: Proizvodi
        type: object
        list: true
        fields:
          - name: id
            label: ID
            type: number
            required: true
          - name: name
            label: Naziv
            type: string
            required: true
          - name: slug
            label: URL slug
            type: string
            required: true
          - name: category
            label: Kategorija
            type: string
            required: true
          - name: description
            label: Opis
            type: text
            required: true
          - name: base_price
            label: Osnovna cena (RSD)
            type: number
            required: true
          - name: discount_percentage
            label: Popust (%)
            type: number
            default: 0
          - name: images
            label: Slike
            type: image
            list: true
            options:
              media: assets/images/products
          - name: colors
            label: Boje
            type: object
            list: true
            fields:
              - name: name
                label: Naziv boje
                type: string
                required: true
              - name: hex
                label: Hex kod
                type: string
                required: true
              - name: price_modifier
                label: Modifikator cene
                type: number
                default: 0
          - name: sizes
            label: Veličine
            type: object
            list: true
            fields:
              - name: name
                label: Naziv veličine
                type: string
                required: true
              - name: price_modifier
                label: Modifikator cene
                type: number
                default: 0
              - name: dimensions
                label: Dimenzije
                type: string
          - name: embroidery_available
            label: Dostupno vez
            type: boolean
            default: false
          - name: embroidery_price
            label: Cena veza (RSD)
            type: number
            default: 0
          - name: stock_status
            label: Status zaliha
            type: select
            required: true
            options:
              values:
                - in_stock
                - low_stock
                - out_of_stock
                - pre_order
          - name: featured
            label: Istaknuto
            type: boolean
            default: false
          - name: new
            label: Novo
            type: boolean
            default: false

  - name: categories
    label: Kategorije
    type: file
    path: _data/categories.json
    format: json
    fields:
      - name: categories
        label: Kategorije
        type: object
        list: true
        fields:
          - name: id
            label: ID
            type: string
            required: true
          - name: name
            label: Naziv
            type: string
            required: true
          - name: slug
            label: URL slug
            type: string
            required: true
          - name: description
            label: Opis
            type: text
          - name: image
            label: Slika
            type: image
            options:
              media: categories
          - name: order
            label: Redosled
            type: number
            default: 0
  # Jekyll configuration
  - name: config
    label: Podešavanja sajta
    path: _config.yml
    type: file
    fields:
  
      # Basic site configuration
      - name: title
        label: Naziv sajta
        type: string
  
      - name: description
        label: Opis sajta
        type: text
  
      - name: baseurl
        label: Base URL
        type: string
  
      - name: url
        label: URL sajta
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
  
      # Store Information
      - name: store
        label: Informacije o prodavnici
        type: object
        fields:
          - name: name
            label: Naziv radnje
            type: string
          - name: owner
            label: Vlasnik
            type: string
          - name: business_name
            label: Poslovno ime
            type: string
          - name: mb
            label: Matični broj (MB)
            type: string
          - name: pib
            label: PIB
            type: string
          - name: address
            label: Adresa
            type: string
          - name: city
            label: Grad
            type: string
          - name: postal_code
            label: Poštanski broj
            type: string
          - name: country
            label: Država
            type: string
          - name: phone
            label: Telefon
            type: string
          - name: email
            label: Email
            type: string
            pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
  
      # Contact Channels
      - name: contact
        label: Kontakt kanali
        type: object
        fields:
          - name: viber
            label: Viber
            type: string
          - name: whatsapp
            label: WhatsApp
            type: string
          - name: facebook_messenger
            label: Facebook Messenger username
            type: string
          - name: sms
            label: SMS broj
            type: string
          - name: call
            label: Broj za poziv
            type: string
  
      # Payment Information
      - name: payment
        label: Detalji plaćanja
        type: object
        fields:
          - name: bank_name
            label: Naziv banke
            type: string
          - name: account_number
            label: Broj računa
            type: string
          - name: account_holder
            label: Vlasnik računa
            type: string
  
      # Shipping Information
      - name: shipping
        label: Dostava
        type: object
        fields:
          - name: courier_name
            label: Kurirska služba
            type: string
          - name: standard_price
            label: Cena standardne dostave
            type: number
          - name: standard_delivery_days
            label: Rok standardne dostave
            type: string
          - name: pickup_delivery_days
            label: Rok za isporuku preuzimanja
            type: string
          - name: cod_fee
            label: Dodatak za pouzeće
            type: number
          - name: free_min_order
            label: Minimalna porudžbina za besplatnu dostavu
            type: number
  
      # Google Apps Script
      - name: google_apps_script
        label: Google Apps Script
        type: object
        fields:
          - name: url
            label: URL
            type: string
  
      # Customization Options
      - name: customization
        label: Podešavanje izrade proizvoda
        type: object
        fields:
          - name: embroidery_price
            label: Cena običnog veza
            type: number
          - name: name_embroidery_price
            label: Cena veza imena
            type: number

      # Build settings
      - name: markdown
        label: Markdown procesor
        type: string
        default: kramdown
  
      - name: permalink
        label: Permalink stil
        type: string
  
      # Collections
      - name: collections
        label: Kolekcije
        type: object
        fields:
          - name: products
            label: Proizvodi kolekcija
            type: object
            fields:
              - name: output
                label: Output
                type: boolean
              - name: permalink
                label: Permalink
                type: string



settings:
  content:
    merge: true
